version: '3'

services:
  data_service:
    build:
      context: ./container/kotlin/data-service
      dockerfile: Dockerfile
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/data_service_db
      - SPRING_DATASOURCE_USERNAME=data_service_db_admin
      - SPRING_DATASOURCE_PASSWORD=data_service
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    container_name: postgres-container
    #    volumes:
    #      - ./container/data/data-service/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=data_service
      - POSTGRES_USER=data_service_db_admin
      - POSTGRES_DB=data_service_db