### Getting projects with name Time Sheet
POST http://{{host}}/load
Content-Type: application/json

{
  "type": "prodactivvity.Project",
  "subQueries": [
    {
      "type": "organization.Customer",
      "parentProperty": "customers",
      "properties": {
        "name": "Foster, Graham and Brown"
      }
    }
  ]
}