GET http://{{host}}/v1/meta

> {%
    client.test("Request passed, returned status is 200", function () {
        client.assert(response.status === 200, "Response status expected 200, Found " + response.status)
    })
%}

###

GET http://{{host}}/v1/meta/agile.Task

###

GET http://{{host}}/v1/meta/core.Client

###

GET http://{{host}}/v1/meta/core.SysUser

###

GET http://{{host}}/v1/meta/organization.AppUser